# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1c252e'
foreground='#a8babb'
cursor='#a8babb'

# Colors
color0='#1c252e'
color1='#5B5457'
color2='#9F4539'
color3='#956456'
color4='#D0B243'
color5='#29798C'
color6='#566E8B'
color7='#a8babb'
color8='#758282'
color9='#5B5457'
color10='#9F4539'
color11='#956456'
color12='#D0B243'
color13='#29798C'
color14='#566E8B'
color15='#a8babb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
