#! /bin/sh

pkill sxhkd; sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Background
feh --bg-scale ~/Pictures/mountain-road.jpg

# Compositor - window effect
pkill compton; compton --config ~/.config/compton/compton.conf &

# Notification
pkill dunst; dunst &

# Top Bar
# This has been inconsistent, sometimes it simply doesn't work
# To debug use the exec variant
#   exec ${HOME}/.config/bspwm/lemonbar/lemonbar-wrapper.sh >> /tmp/lemonbar.out
${HOME}/.config/bspwm/lemonbar/panel
# Alternatively use polybar instead
#   $HOME/.config/polybar/launch.sh

# To debug, spawn a terminal of you choice 
#   alacritty
