#! /bin/sh

pkill sxhkd; sxhkd &

bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d Laptop

bspc config border_width        4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Border
bspc config normal_border_color "#CDFDFD"  # normal window border
bspc config active_border_color "#034366"  # active window, in another monitor
bspc config focused_border_color "#A60241" # currently focused window

# Floating window
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# make it possible to use direction to focus on floating window
bspc config directional_focus_tightness low

# Pywal, set background and colorscheme
# feh --bg-scale ~/Pictures/painterly-sekiro-2560x1440.jpg # alternative setup via feh
wal -i ~/Pictures/painterly-sekiro-2560x1440.jpg 

# Compositor - window effect
pkill compton; compton --config ~/.config/compton/compton.conf &

# Notification
pkill dunst; dunst &

# Conky, drawing on desktop
pkill conky; conky &

# Top Bar
# This has been inconsistent, sometimes it simply doesn't work
# To debug use the exec variant
#   exec ${HOME}/.config/bspwm/lemonbar/lemonbar-wrapper.sh >> /tmp/lemonbar.out
${HOME}/.config/bspwm/lemonbar/panel
# Alternatively use polybar instead
#   $HOME/.config/polybar/launch.sh

# To debug, spawn a terminal of you choice 
#   alacritty

# JAVA apps
# Somehow java apps like intellij doesn't really play nicely with bspwm
# unless you run the following command before hand
# LG3D is one of the window manager that is supported by JAVA apps ...
wmname LG3D
